### ISSUE TITLE
Chapter 16 [-=][-=]\\+ will match mixed - and =

### ISSUE THREAD

**Issue by SnoringFrog** [aharris88/learn-vimscript#1]
Edit: my previous example was incorrect, updated with two working examples of incorrectly-matched strings

The substitution you use for chapter 16 won't quite work correctly, since it will also match lines like this:

    -==========

or this:

    =-------------

`[-=][-=]\\+` should be replaced with `[-=]\\{2,}`

This is fairly trivial and I realize you haven't updated this repo in months, but I stumbled across it when I was Googling to try and solve a problem I had with the chapter 16 exercises, so I thought it might be worth mentioning.

**Comment by aharris88** [comment]
Thanks! I'll look into it.
